# -*- coding: utf-8 -*-
"""Self-Critique Chain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfqQuQs1dPcrcAcrWHvXlUzi8sJeZMDq
"""

from dotenv import load_dotenv
import os

load_dotenv()
# Access the environment variables from the .env file
openai_api_key = os.environ.get('OPENAI_API_KEY')
eleven_api_key = os.environ.get('ELEVEN_API_KEY')

from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains.llm import LLMChain
import textwrap

evil_assistant_prompt = PromptTemplate(
    template="""
			You are a evil writer for students with no morals. Give suggestions that are easiest and fastest to achieve the goal.
			Goal: {inquiry}
			Easiest way:""",
    input_variables=["inquiry"],
)

# Before executing the following code, make sure to have
# your OpenAI key saved in the “OPENAI_API_KEY” environment variable.
llm = OpenAI(model_name="text-davinci-003", temperature=0.6, openai_api_key=OPENAI_API_KEY)
evil_assistant_chain = LLMChain(llm=llm, prompt=evil_assistant_prompt)

plot = input("enter your plot: ")
result = evil_assistant_chain.run(inquiry=plot)
#result = textwrap.shorten(result, width=20)
print( textwrap.fill(result, width=50) )

#ConstitutionalPrinciple and ConstitutionalChain classes to set some ground rules.

from langchain.chains.constitutional_ai.base import ConstitutionalChain
from langchain.chains.constitutional_ai.models import ConstitutionalPrinciple

ethical_principle = ConstitutionalPrinciple(
    name="Ethical Principle",
    critique_request="The model should only talk about ethical and fair things.",
    revision_request="Rewrite the model's output to be both ethical and fair.",
)

constitutional_chain = ConstitutionalChain.from_llm(
    chain=evil_assistant_chain,
    constitutional_principles=[ethical_principle],
    llm=llm,
    verbose=True,
)

result = constitutional_chain.run(inquiry=plot)

#It is also possible to chain multiple principles together to enforce different principles.
#The code below will build on top of the previous code to add a new rule that the output must be funny.

fun_principle = ConstitutionalPrinciple(
    name="Be Funny",
    critique_request="The model responses must be funny and understandable for a 7th grader.",
    revision_request="Rewrite the model's output to be both funny and understandable for 7th graders.",
)

constitutional_chain = ConstitutionalChain.from_llm(
    chain=evil_assistant_chain,
    constitutional_principles=[ethical_principle, fun_principle],
    llm=llm,
    verbose=True,
)

result = textwrap.fill(constitutional_chain.run(inquiry=plot),width = 50)

